// System call numbers
#define SYS_fork      1
#define SYS_exit      2
#define SYS_wait      3
#define SYS_pipe      4
#define SYS_read      5
#define SYS_kill      6
#define SYS_exec      7
#define SYS_fstat     8
#define SYS_chdir     9
#define SYS_dup       10
#define SYS_getpid    11
#define SYS_sbrk      12
#define SYS_pause     13
#define SYS_uptime    14
#define SYS_open      15
#define SYS_write     16
#define SYS_mknod     17
#define SYS_unlink    18
#define SYS_link      19
#define SYS_mkdir     20
#define SYS_close     21
#define SYS_sync      22
#define SYS_psinfo    23
#define SYS_freemem   24
#define SYS_klog      25
#define SYS_waitx     26
#define SYS_fsinfo    27
#define SYS_sysinfo   28
#define SYS_setprio   29
#define SYS_sigaction 30
#define SYS_sigmask   31
#define SYS_sigreturn 32
#define SYS_signal    33
#define SYS_killpg    34
#define SYS_setpgid   35
#define SYS_getpgid   36
#define SYS_tcsetpgrp 37
#define SYS_waitpg    38
#define SYS_jobstate  39
#define SYS_getuid    40
#define SYS_getgid    41
#define SYS_setuid    42
#define SYS_setgid    43
#define SYS_chmod     44
#define SYS_chown     45
#define SYS_ttyecho   46

#define SYS_mmap   47
#define SYS_munmap 48
